# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Eugene Ruby Ded"
email: "sodium229897@gmail.com"
description: "Блог для заметок по Ruby, Rails и PostgreSQL. С болью, с шутками, с продом и 🔥."
baseurl: ""  # не указывай, если размещаешь в корне GitHub Pages (eugene-ruby.github.io)
url: "https://eugene-ruby.github.io"

# SEO и социальные ссылки
twitter_username: ""
github_username: "eugene-ruby"

# Навигация
fixed_navbar: top

# Постоянные ссылки
permalink: /posts/:title:output_ext

# Build settings
remote_theme: "chrisrhymes/bulma-clean-theme@v0.14.0"
plugins:
  - jekyll-toc
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed     # RSS для подписки
  - jekyll-seo-tag  # мета-теги SEO (title, og:image и др.)

# UI настройки темы Bulma Clean
hide_share_buttons: true
footer_text: "© 2025 Заметки деда. Все боли защищены."

# Автогенерация оглавления
toc:
  min_level: 2
  max_level: 3

# Sitemap config (опционально, но можно)
defaults:
  -
    scope:
      path: ""
    values:
      changefreq: "weekly"
      priority: "0.7"

collections:
  products:
    output: true
    permalink: /categories/:name/


# Exclude ненужное
exclude:
  - drafts/*.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - _tools
  - tmp

# Future-proof
future: true
